/// <reference types="vite/client" />

interface ImportMeta {
  readonly env: ImportMetaEnv
}

interface ImportMetaEnv {
  // Auto-generated by env-dts
  readonly VITE_API_BASE_URL: string
  readonly VITE_API_UPLOAD_URL: string
}
