/// <reference types="vite/client" />
interface ImportMeta {
  readonly env: ImportMetaEnv
}

interface ImportMetaEnv {
  // Auto-generated by runtime-config
  readonly VITE_API_BASE_URL: string
  readonly VITE_API_UPLOAD_URL: string
}
