/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Auto-generated by icons-helper

declare module 'virtual:icons-helper' {
  import type { Component } from 'vue'
  export const svgIcons : Array<{ name: SvgIconEnum; icon: Component }>
  
  export const svgIconsMap : Map<SvgIconEnum, Component>
  
  export type SvgIconEnum = 'arrow-right-to-bracket' | 'bars' | 'bug' | 'chart' | 'code' | 'customer' | 'double-arrow-left' | 'double-arrow-right' | 'error' | 'github' | 'home' | 'md' | 'setting' | 'user'
}
