/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Auto-generated by icons-helper

declare module 'virtual:icons-helper' {
  
  export const svgIcons: Array<{ name: SvgIcon; icon: Component }>
  
  export const svgIconsMap: Map<SvgIcon, Component>
  
  export type SvgIcon =  
    | 'arrow-right-to-bracket'
    | 'bars'
    | 'bug'
    | 'chart'
    | 'code'
    | 'customer'
    | 'double-arrow-left'
    | 'double-arrow-right'
    | 'error'
    | 'github'
    | 'home'
    | 'i18n'
    | 'md'
    | 'setting'
    | 'user'
  
}