// Auto-generated by icons-helper
// @ts-expect-error
// @ts-nocheck

import type { Component } from 'vue'

export const svgIcon = [
  {
    name: 'arrow-right-to-bracket',
    icon: SvgIconArrowRightToBracket as Component
  },
  {
    name: 'bars',
    icon: SvgIconBars as Component
  },
  {
    name: 'bug',
    icon: SvgIconBug as Component
  },
  {
    name: 'chart',
    icon: SvgIconChart as Component
  },
  {
    name: 'code',
    icon: SvgIconCode as Component
  },
  {
    name: 'customer',
    icon: SvgIconCustomer as Component
  },
  {
    name: 'double-arrow-left',
    icon: SvgIconDoubleArrowLeft as Component
  },
  {
    name: 'double-arrow-right',
    icon: SvgIconDoubleArrowRight as Component
  },
  {
    name: 'error',
    icon: SvgIconError as Component
  },
  {
    name: 'github',
    icon: SvgIconGithub as Component
  },
  {
    name: 'home',
    icon: SvgIconHome as Component
  },
  {
    name: 'md',
    icon: SvgIconMd as Component
  },
  {
    name: 'setting',
    icon: SvgIconSetting as Component
  },
  {
    name: 'user',
    icon: SvgIconUser as Component
  }
] as const

export const svgIconMap = svgIcon.reduce((map, { name, icon }) => {
  map.set(name, icon)
  return map
}, new Map<SvgIconEnum, Component>())

export type SvgIconEnum = (typeof svgIcon)[number]['name']
